"""new fields in user model

Revision ID: 57688560c74d
Revises: eed3b0589ea7
Create Date: 2020-03-24 21:48:07.690491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57688560c74d'
down_revision = 'eed3b0589ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
